### ISSUE TITLE
功能建议，希望大大考虑为谢

### ISSUE THREAD

**Issue by chineselzh** [greenzorro/bitcron-colachan#1]
太喜欢这个主题了，个人认为这是目前最好的bitcron主题，没有之一！
但是使用中有一点点小遗憾，希望大大能增加一个**文章置顶**功能，就是某篇文章不改变发布或更新时间的前提下放到第一位置！请考虑一下，谢谢！
非常感谢！

**Comment by greenzorro** [comment]
谢谢你的建议哈，我要去研究一下。这个文章置顶功能能不能实现，取决于Bitcron的API了，并不是我的模板可以决定的。如果有我会加进来。

**Comment by chineselzh** [comment]
@greenzorro 感谢大大的热心回答及研究！谢谢！
另外：您的主页上的 **电影收藏** 和 **小玩意**也是用markdown实现的么？用的smartpage？我不懂CSS，能不能将这两页的 markdown 效果代码帖一下？无限感激！

**Comment by greenzorro** [comment]
哎……那几个特殊页面目前还是写死的，静态页面。我是打算改成smartpage的，拖延症拖到现在，哈哈。我改好了会更新到这里的。

**Comment by chineselzh** [comment]
你的主页文章有个**目录**功用，我使用了您的模板但没有，是不是也没有开放？还是写死的？呵呵。。。

**Comment by greenzorro** [comment]
噢，这个不是死的。你只要在bitcron的网页后台打开toc就有了。

**Comment by depthsky2016** [comment]
很棒的主题，也正在使用中，做了一些调整，有一个小小的问题，就是如何能让主题正文页面能支持 markdown 语法？好像正文的CSS限制了markdown语法，像无序列表有序列表好像都不能实现，谢谢。

**Comment by greenzorro** [comment]
你的意思是，想在文章的正文显示markdown的源码？
