### ISSUE TITLE
关于搜索

### ISSUE THREAD

**Issue by ljes** [greenzorro/bitcron-colachan#2]
大大您好，感谢带来如此优秀的主题！
有个小建议希望大大考虑：
希望在搜索框输入关键字回车后，封面页能够自动上滑，这样搜索后能直接呈现结果，而不是手动再往下拉才能看到搜索结果！
谢谢大大！

**Comment by greenzorro** [comment]
好建议，谢谢，我看看如何实现

**Comment by chineselzh** [comment]
@greenzorro 大大，我看您的主页已经实现了搜索后封面自动上滑，为什么我在这里下载模板放到目录里上传后无法实现这个效果呢？
谢谢！

**Comment by greenzorro** [comment]
我的最新模板已经push到这里了。不过实现这个效果的原理不是搜索后自动上滑，而是给首页加了一个特殊class，只在首页显示封面，其他所有页面都不显示封面。我应该有某个标签是有index这个class名的，js会判断当前页面是不是首页，不是的话就不会显示封面。你看看是不是少了class名或者哪里没对上？
