### ISSUE TITLE
system default comments code changed

### ISSUE THREAD

**Issue by WangHong-yang** [greenzorro/bitcron-colachan#4]
Bitcron has revised its code for system default comments. 

Just to change to:
`//- 系统评论框
    //- +post.comments_as_html()`
in "/include/comments.jade"

Please check
it out here: https://mr-why.com/machinelearning/directional-edge-box

**Comment by greenzorro** [comment]
Thanks for reminding :)

**Comment by WangHong-yang** [comment]
> Thanks for reminding :)

np :)
