### ISSUE TITLE
如何修改手机浏览器chrome和safari添加到主屏幕

### ISSUE THREAD

**Issue by daidaidaiok** [greenzorro/bitcron-colachan#5]
如何修改手机浏览器chrome和safari添加到主屏幕时显示的logo和标题

**Comment by greenzorro** [comment]
你是不是想问添加到手机桌面后显示的图标？

图标的位置在 template > images > favicons ，把那一批图标换掉就行了。可以用这个工具来批量生成：
[https://realfavicongenerator.net/](https://realfavicongenerator.net/)

**Comment by daidaidaiok** [comment]
还有标题，我不知道如何修改标题

**Comment by daidaidaiok** [comment]
谢谢 你的推荐，真是一个不错的网站

**Comment by greenzorro** [comment]
标题应该就是网站的title属性，这个要么是在base.jade里，要么是在include/header.jade里
